//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.08 at 11:33:23 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/ws/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.carlosu.ws.webservice.domain;
