//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:25:29 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://carlosu.net/ws/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.carlosu.ws.domain;
